from flask import Blueprint, request, jsonify

tournament_blueprint = Blueprint("tournament", __name__)


@tournament_blueprint.route("/", methods = ["POST"])
def create_tounrament():
    if request.method == "POST":
        print(request.form)
        return request.form



@tournament_blueprint.route("/<int:tournament_id>", methods = ['GET',"POST"])
def get_tournament(tournament_id:int):
    if request.method == "GET":
        return str(tournament_id)
    if request.method == "POST":
        return jsonify([
            {
                "tournament_id": tournament_id,
                "tournament_admin_id": "autogenerated_tournament_admin_uuid",
                "tournament_admin_email": "user_generated"
            }
        ])

@tournament_blueprint.route("/admin/<tournament_admin_uuid>")
def get_tournament_admin_page(tournament_admin_uuid:str):
    return tournament_admin_uuid

